<a href="https://colab.research.google.com/github/kirtisingh-001/kirtisingh-001-DataScience_Day_wise_work/blob/main/Weekly_assessment_Capstone_project_day12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import files
uploaded = files.upload()

Saving DatasetCapstoneProject3.xlsx to DatasetCapstoneProject3 (1).xlsx


In [8]:
#Smart Marketing Prediction System (ML Pipeline Project)
#Scenario
#A fast-growing e-commerce company called ShopEasy is struggling with inefficient marketing campaigns.
#Every day thousands of users visit their website. The marketing team spends a large amount of money showing ads, discounts, and promotional emails, but they don't know which customers are actually likely to buy something.
#Currently:
#Many customers browse but never purchase
#Marketing money is wasted on the wrong users
#The company wants to predict purchase probability
#The data science team has been asked to build a machine learning system that predicts whether a customer will purchase a product during a session.
#If the system predicts high probability of purchase, the system will:
#show personalized product recommendations
#offer targeted discounts
#prioritize marketing campaigns
#If the system predicts low probabil
# Smart Marketing Prediction System
# ML Pipeline using Scikit-Learn


import pandas as pd # python library for data manipulation
import numpy as np #python library for mathematical operations
from sklearn.model_selection import train_test_split #To divide data into training ,testing and splitting data to train the model to check model accuracy,avoid overfitting and false accuracy
from sklearn.model_selection import GridSearchCV #to find best learning hyperparameter
from sklearn.preprocessing import OneHotEncoder #to convert categorical value to numerical value
from sklearn.preprocessing import StandardScaler #so that large valued features do not dominate small value features
from sklearn.compose import ColumnTransformer #apply different preprocessing steps to different types of features (columns) in a dataset.
from sklearn.pipeline import Pipeline #combines all multiple steps into one object
from sklearn.ensemble import RandomForestClassifier #predict whether a customer will purchase a product during a session by making multiple decision trees
from sklearn.metrics import accuracy_score #to measure how accurate a machine learning model’s predictions are.
from sklearn.metrics import classification_report #to evaluate classification models
from sklearn.metrics import confusion_matrix #table to evaluate classification models

data = pd.read_excel("DatasetCapstoneProject3.xlsx") #dataset path updation
print("Dataset Shape:", data.shape)
print("\nFirst 5 rows:")
print(data.head())
target = "Purchased" #Define Target Variable
X = data.drop(target, axis=1) #Removing the target variable so that model does not cheat,axis=1 means column wise
y = data[target] #y is storing the target variable
categorical_features = X.select_dtypes(include=['object']).columns #Identify Feature Types
numerical_features = X.select_dtypes(exclude=['object']).columns
print("\nCategorical Features:", list(categorical_features))
print("Numerical Features:", list(numerical_features))
# Preprocessing Pipelines
# Numerical pipeline
num_pipeline = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)
# Categorical pipeline
cat_pipeline = Pipeline(
    steps=[
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]
)
# Combine preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ("num", num_pipeline, numerical_features),
        ("cat", cat_pipeline, categorical_features)
    ]
)
# 6. Create Full ML Pipeline
pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", RandomForestClassifier(random_state=42))
    ]
)
# 7. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
# 8. Hyperparameter Tuning
param_grid = {
    "model__n_estimators": [100, 200], #Number of decision trees in the random forest.
    "model__max_depth": [None, 10, 20], #Maximum depth of each decision tree.
    "model__min_samples_split": [2, 5] #Minimum number of samples required to split a node.
}

grid_search = GridSearchCV( #find the best learning hyperparameter
    estimator=pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1 #how many CPU cores are used to run tasks in parallel.
)
# Train model
grid_search.fit(X_train, y_train)
print("\nBest Parameters Found:")
print(grid_search.best_params_)
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
print("\nModel Accuracy:")
print(accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
probabilities = best_model.predict_proba(X_test)[:, 1] #select all rows and column index 1
print("\nPurchase Probabilities (First 10):")
print(probabilities[:10])
decision = [
    "Target Marketing" if p > 0.6 else "Do Not Target"
    for p in probabilities
]
results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred,
    "Purchase_Probability": probabilities,
    "Marketing_Decision": decision
})
print("\nSample Marketing Decisions:")
print(results.head())
# Business Insights
targeted_customers = results[results["Marketing_Decision"] == "Target Marketing"]
print("\nNumber of Customers to Target:", len(targeted_customers))
print("Total Customers Evaluated:", len(results))

Dataset Shape: (15, 10)

First 5 rows:
   CustomerID  Age  Gender   Device  Traffic_Source  Time_on_Website  \
0           1   23    Male   Mobile    Social Media                5   
1           2   35  Female  Desktop   Search Engine               12   
2           3   29    Male   Tablet    Social Media                8   
3           4   41  Female   Mobile  Email Campaign               15   
4           5   22  Female  Desktop          Direct                4   

   Pages_Visited  Ad_Clicks  Previous_Purchases  Purchased  
0              3          1                   0          0  
1              8          3                   2          1  
2              5          2                   1          0  
3             10          4                   3          1  
4              2          0                   0          0  

Categorical Features: ['Gender', 'Device', 'Traffic_Source']
Numerical Features: ['CustomerID', 'Age', 'Time_on_Website', 'Pages_Visited', 'Ad_Clicks', 'Previous

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(



Best Parameters Found:
{'model__max_depth': None, 'model__min_samples_split': 2, 'model__n_estimators': 100}

Model Accuracy:
1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3


Confusion Matrix:
[[2 0]
 [0 1]]

Purchase Probabilities (First 10):
[0.06 0.68 0.02]

Sample Marketing Decisions:
    Actual  Predicted  Purchase_Probability Marketing_Decision
9        0          0                  0.06      Do Not Target
11       1          1                  0.68   Target Marketing
0        0          0                  0.02      Do Not Target

Number of Customers to Target: 1
Total Customers Evaluated: 3


In [14]:
from google.colab import files
uploaded = files.upload()

Saving DatasetCapstoneProject4.csv to DatasetCapstoneProject4 (1).csv


In [15]:
#Capstone Project 4
#Project Scenario
#Smart Traffic Sign Recognition System
#Scenario
#A city is building a Smart Traffic Monitoring System to improve road safety.
#Every intersection in the city will have cameras that detect traffic signs automatically.
#The system must recognize different road signs such as:
#Stop sign
#Speed limit sign
#Pedestrian crossing sign
#The system will be used in autonomous vehicles and traffic monitoring cameras.
#However, the engineers discovered two challenges:
#1️. First, the system must understand basic classification logic (learning from features).
#2️. Second, it must classify images of traffic signs captured by cameras.
#To solve this, the engineering team decided to build the system in two stages.

import pandas as pd # python library for data manipulation
import numpy as np #python library for mathematical operations

from sklearn.model_selection import train_test_split ##To divide data into training ,testing and splitting data to train the model to check model accuracy,avoid overfitting and false accuracy
from sklearn.linear_model import Perceptron #It allows you to create and train a perceptron model for classification tasks.
#A Perceptron is the simplest type of neural network used for binary classification
from sklearn.metrics import accuracy_score #to measure how accurate a machine learning model’s predictions are.
from sklearn.metrics import classification_report  #to evaluate classification models
from sklearn.metrics import confusion_matrix #table to evaluate classification models

data = pd.read_csv("DatasetCapstoneProject4.csv")
#Define Features and Target
X = data.drop("Stop_Sign", axis=1) #Removing the target variable so that model does not cheat leading to data leakage,axis=1 means column wise
y = data["Stop_Sign"]

#Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42
)
#Train Perceptron Model
model = Perceptron(max_iter=1000) #max_iter sets the maximum number of training iteration
model.fit(X_train, y_train) #tells the model to learn patterns from the training dataset.

#Make Predictions
y_pred = model.predict(X_test)
print("\nPredictions:")
print(y_pred)

#Model Evaluation
print("\nAccuracy:")
print(accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

#Test with New Traffic Sign
# The new_sign array must have 5 features (columns) to match the training data
# Example: [Sign_ID, Red_Color_Intensity, Circular_Shape, Text_Present, Edge_Count]
new_sign = np.array([[11, 0.88, 0, 1, 7]])  # Example: likely STOP sign with 5 features
prediction = model.predict(new_sign)
print("\nNew Sign Prediction:")
print("STOP Sign" if prediction[0]==1 else "NOT STOP Sign")


Predictions:
[0 1 0]

Accuracy:
0.3333333333333333

Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.00      0.00      0.00         1

    accuracy                           0.33         3
   macro avg       0.25      0.25      0.25         3
weighted avg       0.33      0.33      0.33         3


Confusion Matrix:
[[1 1]
 [1 0]]

New Sign Prediction:
NOT STOP Sign


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  warnings.warn(
